export const LOCAL_STORAGE_KEYS = {
    EMPLOYEE: 'employee_data',
    TOKEN: 'auth_token',
    LAST_VISITED_PAGE: 'lastVisitedPage',
    DAPARTMENT_MASTER_SELECTED_COLUMNS: 'departmentMaster.selectedColumns',
    DESIGNATION_MASTER_SELECTED_COLUMNS: 'designationMaster.selectedColumns',
    EMPLOYEE_MASTER_SELECTED_COLUMNS: 'employeeMaster.selectedColumns',
    BRANCH_MASTER_SELECTED_COLUMNS: 'branchMaster.selectedColumns',
    BRANCH_ASSOCIATIONS_MASTER_SELECTED_COLUMNS: 'branchAssociationsMaster.selectedColumns',
    ASSET_MASTER_SELECTED_COLUMNS: 'assetMaster.selectedColumns',
    ASSET_MAPPING_MASTER_SELECTED_COLUMNS: 'assetMappingMaster.selectedColumns',
    DEDUCTION_MASTER_SELECTED_COLUMNS: 'deductionMaster.selectedColumns',
    EARNING_MASTER_SELECTED_COLUMNS: 'earningMaster.selectedColumns',
    VENDOR_SELECTED_COLUMNS: 'vendor.selectedColumns',
    COMPANY_MASTER_SELECTED_COLUMNS: 'companyMaster.selectedColumns',
    BANK_LIST_MASTER_SELECTED_COLUMNS: 'bankListMaster.selectedColumns',
    HOLIDAY_MASTER_SELECTED_COLUMNS: 'holidayMaster.selectedColumns',
    HOLIDAY_MAPPING_MASTER_SELECTED_COLUMNS: 'holidayMappingMaster.selectedColumns',
    LEAVE_ENCASHMENT_MASTER_SELECTED_COLUMNS: 'leaveEncashmentMaster.selectedColumns',
    LEAVE_TYPE_MASTER_SELECTED_COLUMNS: 'leaveTypeMaster.selectedColumns',
    SHIFT_MASTER_SELECTED_COLUMNS: 'shiftMaster.selectedColumns',
    SHIFT_MAPPING_MASTER_SELECTED_COLUMNS: 'shiftMappingMaster.selectedColumns',
    WEEK_OFF_MAPPING_MASTER_SELECTED_COLUMNS: 'weekOffMappingMaster.selectedColumns',
    WEEK_OFF_MASTER_SELECTED_COLUMNS: 'weekOffMaster.selectedColumns',
    TNC_MASTER_SELECTED_COLUMNS: 'tncMaster.selectedColumns',
    MENU_MODULE: 'menuModule',
    COUNTRY_STATE_DISTRICT_CITY_VILLAGE_MASTER: 'country_state_district_city_village_data',
} as const